'use server';

import { createSupabaseServerClient } from '@/libs/supabase/supabase-server-client';
import { ActionResponse } from '@/types/action-response';

interface AssignGridNumbersParams {
  contestId: string;
  rowNumbers: number[] | null;
  colNumbers: number[] | null;
  autoGenerate: boolean;
}

interface AssignGridNumbersResult {
  rowNumbers: number[];
  colNumbers: number[];
  numbersAutoGenerated: boolean;
}

/**
 * Shuffles an array of numbers 0-9 using Fisher-Yates algorithm
 */
function shuffleNumbers(): number[] {
  const nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  for (let i = nums.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [nums[i], nums[j]] = [nums[j], nums[i]];
  }
  return nums;
}

/**
 * Validates that an array contains exactly the digits 0-9 with no duplicates
 */
function isValidNumberArray(arr: number[] | null): arr is number[] {
  if (!arr || arr.length !== 10) return false;
  const sorted = [...arr].sort((a, b) => a - b);
  return sorted.every((num, idx) => num === idx);
}

/**
 * Assigns grid numbers (row and column headers) to a contest.
 * Only the owner can assign numbers, and only when contest is not in_progress or completed.
 */
export async function assignGridNumbers({
  contestId,
  rowNumbers,
  colNumbers,
  autoGenerate,
}: AssignGridNumbersParams): Promise<ActionResponse<AssignGridNumbersResult>> {
  const supabase = await createSupabaseServerClient();

  // Verify user is authenticated
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return { data: null, error: { message: 'You must be logged in' } };
  }

  // Fetch contest to verify ownership and status
  const { data: contest, error: fetchError } = await supabase
    .from('contests')
    .select('id, owner_id, status')
    .eq('id', contestId)
    .single();

  if (fetchError || !contest) {
    return { data: null, error: { message: 'Contest not found' } };
  }

  // Verify ownership
  if (contest.owner_id !== user.id) {
    return { data: null, error: { message: 'You do not have permission to modify this contest' } };
  }

  // Verify contest status allows number assignment
  if (contest.status === 'in_progress' || contest.status === 'completed') {
    return {
      data: null,
      error: { message: 'Cannot assign numbers to a contest that is in progress or completed' },
    };
  }

  let finalRowNumbers: number[];
  let finalColNumbers: number[];
  let numbersAutoGenerated: boolean;

  if (autoGenerate) {
    // Auto-generate shuffled numbers
    finalRowNumbers = shuffleNumbers();
    finalColNumbers = shuffleNumbers();
    numbersAutoGenerated = true;
  } else {
    // Validate manually provided numbers
    if (!isValidNumberArray(rowNumbers)) {
      return {
        data: null,
        error: { message: 'Row numbers must contain exactly 10 unique digits (0-9)' },
      };
    }
    if (!isValidNumberArray(colNumbers)) {
      return {
        data: null,
        error: { message: 'Column numbers must contain exactly 10 unique digits (0-9)' },
      };
    }
    finalRowNumbers = rowNumbers;
    finalColNumbers = colNumbers;
    numbersAutoGenerated = false;
  }

  // Update the contest with the assigned numbers
  const { error: updateError } = await supabase
    .from('contests')
    .update({
      row_numbers: finalRowNumbers,
      col_numbers: finalColNumbers,
      numbers_auto_generated: numbersAutoGenerated,
    })
    .eq('id', contestId)
    .eq('owner_id', user.id);

  if (updateError) {
    return {
      data: null,
      error: { message: `Failed to assign grid numbers: ${updateError.message}` },
    };
  }

  // Send numbers revealed emails (non-blocking)
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (supabaseUrl && anonKey) {
      fetch(`${supabaseUrl}/functions/v1/send-numbers-revealed-emails`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${anonKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ contestId }),
      }).catch((err) => console.error('Failed to trigger numbers revealed emails:', err));
    }
  } catch (error) {
    // Log but don't fail the action
    console.error('Error triggering numbers revealed emails:', error);
  }

  return {
    data: {
      rowNumbers: finalRowNumbers,
      colNumbers: finalColNumbers,
      numbersAutoGenerated,
    },
    error: null,
  };
}

