'use server'

import { ContestStatus } from '@/features/contests/constants';
import { ActionResponse } from '@/types/action-response';

import { withContestOwnership } from '../middleware/auth-middleware';

interface AssignGridNumbersParams {
  contestId: string;
  rowNumbers: number[] | null;
  colNumbers: number[] | null;
  autoGenerate: boolean;
}

interface AssignGridNumbersResult {
  rowNumbers: number[];
  colNumbers: number[];
  numbersAutoGenerated: boolean;
}

function shuffleNumbers(): number[] {
  const nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  for (let i = nums.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [nums[i], nums[j]] = [nums[j], nums[i]];
  }
  return nums;
}

function isValidNumberArray(arr: number[] | null): arr is number[] {
  if (!arr || arr.length !== 10) return false;
  const sorted = [...arr].sort((a, b) => a - b);
  return sorted.every((num, idx) => num === idx);
}

export async function assignGridNumbers({
  contestId,
  rowNumbers,
  colNumbers,
  autoGenerate,
}: AssignGridNumbersParams): Promise<ActionResponse<AssignGridNumbersResult>> {
  return withContestOwnership<AssignGridNumbersResult>(contestId, async (user, supabase, contest) => {
    // Verify contest status allows number assignment
    if (contest.status === ContestStatus.IN_PROGRESS || contest.status === ContestStatus.COMPLETED) {
      throw new Error('Cannot assign numbers to a contest that is in progress or completed');
    }

    let finalRowNumbers: number[];
    let finalColNumbers: number[];
    let numbersAutoGenerated: boolean;

    if (autoGenerate) {
      finalRowNumbers = shuffleNumbers();
      finalColNumbers = shuffleNumbers();
      numbersAutoGenerated = true;
    } else {
      if (!isValidNumberArray(rowNumbers)) {
        throw new Error('Row numbers must contain exactly 10 unique digits (0-9)');
      }
      if (!isValidNumberArray(colNumbers)) {
        throw new Error('Column numbers must contain exactly 10 unique digits (0-9)');
      }
      finalRowNumbers = rowNumbers;
      finalColNumbers = colNumbers;
      numbersAutoGenerated = false;
    }

    // Update the contest
    const { error: updateError } = await supabase
      .from('contests')
      .update({
        row_numbers: finalRowNumbers,
        col_numbers: finalColNumbers,
        numbers_auto_generated: numbersAutoGenerated,
      })
      .eq('id', contestId)
      .eq('owner_id', user.id);

    if (updateError) {
      throw new Error(`Failed to assign grid numbers: ${updateError.message}`);
    }

    // Send numbers revealed emails (non-blocking)
    try {
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
      const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

      if (supabaseUrl && anonKey) {
        fetch(`${supabaseUrl}/functions/v1/send-numbers-revealed-emails`, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${anonKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ contestId }),
        }).catch(() => {}); // Silently fail
      }
    } catch {
      // Silently fail - don't block number assignment
    }

    return {
      rowNumbers: finalRowNumbers,
      colNumbers: finalColNumbers,
      numbersAutoGenerated,
    };
  })();
}