# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'en-US'
early_access: false

reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  collapse_walkthrough: false
  review_status: true
  
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - staging

  tools:
    eslint:
      enabled: true
    biome:
      enabled: false

  path_instructions:
    # Next.js special files - framework requires default exports
    - path: '**/app/**/{page,layout,error,loading,not-found,template,default}.{ts,tsx}'
      instructions: |
        Review for Next.js best practices. Note: default exports are required by the framework for these files.
    
    # Next.js middleware - framework requires default export
    - path: '**/middleware.{ts,tsx}'
      instructions: |
        Review middleware patterns. Note: default export is required by Next.js.
    
    # Everything else - enforce our coding standards
    - path: '**/*.{ts,tsx,js,jsx}'
      instructions: |
        ## Code Review Standards
        
        **Critical:**
        1. No `any` - use `unknown`, generics, or specific types
        2. Named exports only - EXCEPT for Next.js special files (page, layout, etc.)
        3. Never expose SUPABASE_SERVICE_ROLE_KEY in client code
        4. `const` by default - use `let` only when reassignment needed. Never `var`
        5. Strict equality - always `===`/`!==` (exception: `== null` for null/undefined)
        6. Proper error handling - throw `new Error()` objects, not primitives
        7. Type annotations for exported functions - explicit parameters and return types
        8. Use `import type` for type-only imports
        
        **Important:**
        - KISS - simple solutions over complex ones
        - DRY (Rule of Three) - extract after 3+ repetitions
        - Descriptive names without comments
        - Prefer `interface` for objects, `type` for unions/primitives
        - Avoid `@ts-ignore`, `@ts-expect-error`, `@ts-nocheck`
        
        **React:**
        - Functional components with hooks
        - One component per file
        - No premature optimization (memo, useMemo, useCallback)
        
        Style guide: https://google.github.io/styleguide/tsguide.html

chat:
  auto_reply: true