# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'en-US'

early_access: false

reviews:
  # NOTE: Using relaxed settings for initial adoption. Once team is comfortable
  # with CodeRabbit, consider changing to profile: 'assertive' and
  # request_changes_workflow: true for stricter, blocking reviews.
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  collapse_walkthrough: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - staging

  tools:
    eslint:
      enabled: true
    biome:
      enabled: true

  path_instructions:
    - path: '**/*.{ts,tsx,js,jsx}'
      instructions: |
        ## Code Review Checklist

        Focus on these high-impact rules. Style enforcement is handled by ESLint/Biome.
        Full style guide: https://google.github.io/styleguide/tsguide.html

        ### 🔴 Critical Rules (flag these)

        1. **No `any`** — Use `unknown`, generics, or specific types. If unavoidable, add a comment explaining why.
        2. **Named exports only** — No `export default`. Use `export function`, `export const`, `export class`.
        3. **`const` by default** — Use `let` only when reassignment is needed. Never use `var`.
        4. **Strict equality** — Always `===`/`!==`. Exception: `== null` for null/undefined check.
        5. **Proper error handling** — Throw `new Error()` objects, never primitives. Don't leave empty catch blocks.
        6. **Type annotations for public APIs** — Exported functions must have explicit parameter and return types.
        7. **Use `import type`** — For type-only imports: `import type { Foo } from './types'`

        ### 🟡 Important Rules (suggest improvements)

        8. **KISS** — Favor simple solutions. If code needs extensive comments to explain, it's too complex.
        9. **DRY (Rule of Three)** — Extract after seeing the same pattern 3+ times. Some duplication beats wrong abstraction.
        10. **Descriptive names** — Names should be clear without comments. No Hungarian notation (`strName`), no `I` prefix on interfaces.
        11. **Minimize exports** — Only export what's needed. Keep internal helpers private.
        12. **Prefer `interface`** — Use `interface` for object types, `type` for unions/tuples/primitives.
        13. **No `@ts-ignore`** — Avoid `@ts-ignore`, `@ts-expect-error`, `@ts-nocheck`. Fix the type issue instead.

        ### ⚛️ React Rules (for .tsx/.jsx)

        14. **Functional components** — Use hooks, not class components.
        15. **Single responsibility** — One main component per file. Extract logic to custom hooks.
        16. **No premature optimization** — Avoid `React.memo`, `useMemo`, `useCallback` unless there's a measured perf issue.

        ### 🛠️ Automated Tooling

        These are enforced by tooling and don't need manual review:
        - Formatting (Prettier)
        - Import ordering
        - Unused variables
        - Consistent syntax style

        ESLint/Biome and TSConfig strict mode handle most style rules automatically.

chat:
  auto_reply: true
